config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :skills
  root "pages#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/skill.rb
class Skill < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :is_admin? 

    private
    def is_admin?
        if current_user&.admin?
        else 
            redirect_to root_path
        end
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @skills = Skill.all
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :set_skill, only: %i[ show edit update destroy ]
  before_action :is_admin?

  # GET /skills or /skills.json
  def index
    @skills = Skill.all
  end

  # GET /skills/1 or /skills/1.json
  def show
  end

  # GET /skills/new
  def new
    @skill = Skill.new
  end

  # GET /skills/1/edit
  def edit
  end

  # POST /skills or /skills.json
  def create
    @skill = Skill.new(skill_params)

    respond_to do |format|
      if @skill.save
        format.html { redirect_to skill_url(@skill), notice: "Skill was successfully created." }
        format.json { render :show, status: :created, location: @skill }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /skills/1 or /skills/1.json
  def update
    respond_to do |format|
      if @skill.update(skill_params)
        format.html { redirect_to skill_url(@skill), notice: "Skill was successfully updated." }
        format.json { render :show, status: :ok, location: @skill }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /skills/1 or /skills/1.json
  def destroy
    @skill.destroy!

    respond_to do |format|
      format.html { redirect_to skills_url, notice: "Skill was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_skill
      @skill = Skill.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def skill_params
      params.require(:skill).permit(:name, :description, :icon)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/layouts/_navbar.html.erb
 <!-- Navigation-->
  <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand" href="#page-top">Ashim Portfolio</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars ms-1"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav text-uppercase ms-auto py-4 py-lg-0">
          <li class="nav-item"><a class="nav-link" href="#services">Skills</a></li>
          <li class="nav-item"><a class="nav-link" href="#portfolio">Portfolio</a></li>
          <li class="nav-item"><a class="nav-link" href="#about">About</a></li>
          <li class="nav-item"><a class="nav-link" href="#team">Team</a></li>
          <li class="nav-item"><a class="nav-link" href="#contact">Contact</a></li>
        </ul>
      </div>
    </div>
  </nav>    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="/startbootstrap-agency-gh-pages/css/styles.css?v=1" rel="stylesheet">
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <%# <link href="startbootstrap-agency-gh-pages/css/styles.css" rel="stylesheet" /> %>
  </head>
  <body id="page-top">
    <% if controller_name == 'pages'%>
      <%= render 'layouts/navbar'%>
    <%end%>
    <%= yield %>
  </body>
  <footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="/startbootstrap-agency-gh-pages/js/scripts.js"></script>
    <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
    <!-- * *                               SB Forms JS                               * *-->
    <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
    <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
    <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
  </footer>
</html>

app/views/skills/_form.html.erb
<%= form_with(model: skill) do |form| %>
  <% if skill.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(skill.errors.count, "error") %> prohibited this skill from being saved:</h2>

      <ul>
        <% skill.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul> 
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :icon, style: "display: block" %>
    <%= form.text_field :icon %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/skills/_skill.html.erb
<div id="<%= dom_id skill %>">
  <p>
    <strong>Name:</strong>
    <%= skill.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= skill.description %>
  </p>

  <p>
    <strong>Icon:</strong>
    <%= skill.icon %>
  </p>

</div>

app/views/skills/edit.html.erb
<h1>Editing skill</h1>

<%= render "form", skill: @skill %>

<br>

<div>
  <%= link_to "Show this skill", @skill %> |
  <%= link_to "Back to skills", skills_path %>
</div>

app/views/skills/index.html.erb
<table class="table table-dark">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Description</th>
      <th scope="col">Icon</th>
      <th scope="col">Edit</th>
      <th scope="col">Delete</th>
    </tr>
  </thead>
  <tbody>
    <% @skills.each.with_index do |skill, index| %>
      <tr>
        <th scope="row"><%= index +1 %></th>
        <td><%= skill.name %></td>
        <td><%= skill.description %></td>
        <td><i class='fas <%= skill.icon%>'></i></td>
        <td><%= link_to "Edit", edit_skill_path(skill) , class: 'btn btn-primary' %></td>
        <td><%= link_to "Delete", skill, method: :delete, class: 'btn btn-danger' %></td>
      </tr>
    <%end%>
  </tbody>
</table>
<div class="button-group" role="group">
  <%= link_to "Home", root_path, class: 'btn btn-success '%>
  <%= link_to "New Skill", new_skill_path, class: 'btn btn-primary'%>
  <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'btn btn-danger'%>
</div>

app/views/skills/new.html.erb
<div class="container" style="margin-top:10em">
  <h1>New skill</h1>
  <%= render "form", skill: @skill %>
  <br>
  <div>
    <%= link_to "Back to skills", skills_path %>
  </div>
</div>

app/views/skills/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @skill %>

<div>
  <%= link_to "Edit this skill", edit_skill_path(@skill) %> |
  <%= link_to "Back to skills", skills_path %>

  <%= button_to "Destroy this skill", @skill, method: :delete %>
</div>